"""
Adversarial Stress Test — Session 081.

SEPARATE from the organic Kill Test (test_kill_condition.py).

Purpose: verify substrate behaviour under realistic stress — the kinds of
mistakes a real user makes when using a research notebook without thinking
carefully about categories and consistency.

ChatGPT advisory (Session 081): "The Kill Test data was generated by people
who already understand the substrate. That is a friendly environment. We need
to test against adversarial input too."

This is NOT the 4-week Kill Test. It is a one-time stress pass to confirm
the substrate handles messy, realistic input correctly.

Adversarial packets:
  A — Contradictory corrections filed in rapid succession
  B — Category misuse (wrong category for the content type)
  C — Malformed / edge-case content (empty string, None-like, very long)
  D — Superseded conclusions (a finding overridden by a later one)
  E — Duplicate exact content (same item proposed twice)

Usage:
  cd runtime/v0.1
  python3 tests/test_adversarial_stress.py

Session 081.
"""
from __future__ import annotations

import sys, os, tempfile
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from notebook.governed_notebook import GovernedNotebook


def section(title: str) -> None:
    print(f"\n{'=' * 68}")
    print(f"  {title}")
    print('=' * 68)


def show(label: str, result) -> None:
    status = result.status
    marker = {"admitted": "✓", "conflict": "⚡", "gap": "◻", "error": "✗"}.get(status, "?")
    print(f"  {marker} [{status.upper():10}] {label}")
    if result.status == "conflict":
        print(f"              conflicts with: {[c[:8] for c in result.conflict_with]}")
    if result.status == "gap":
        print(f"              gap_category: {result.gap_category}")


def run_adversarial_stress() -> None:
    print("=" * 68)
    print("  RITAM ADVERSARIAL STRESS TEST — Session 081")
    print("  Tests substrate behaviour under realistic messy input.")
    print("  This is NOT the 4-week Kill Test.")
    print("=" * 68)

    with tempfile.TemporaryDirectory() as tmp:
        nb = GovernedNotebook(
            storage_path=tmp,
            categories=["empirical-finding", "hypothesis", "question", "method-note"]
        )

        # ------------------------------------------------------------------
        # Packet A — Contradictory corrections filed in rapid succession
        # A user keeps changing their mind about the same finding.
        # ------------------------------------------------------------------
        section("PACKET A — Contradictory corrections in rapid succession")
        print("  Scenario: researcher keeps revising a finding.")

        r1 = nb.add_entry("Governance overhead is negligible at small scale.", "empirical-finding", "session-010")
        show("v1: governance overhead negligible", r1)

        r2 = nb.add_entry("Governance overhead is significant at small scale.", "empirical-finding", "session-020")
        show("v2: governance overhead significant (contradicts v1)", r2)

        r3 = nb.add_entry("Governance overhead depends on substrate depth, not scale.", "empirical-finding", "session-030")
        show("v3: overhead is depth-dependent (contradicts both)", r3)

        contras_a = nb.list_contradictions("empirical-finding")
        print(f"\n  Contradictions quarantined: {len(contras_a)}")
        print(f"  Expected: all three versions preserved in quarantine, none silently overwritten.")

        # ------------------------------------------------------------------
        # Packet B — Category misuse
        # User files things in wrong categories.
        # ------------------------------------------------------------------
        nb2 = GovernedNotebook(
            storage_path=tmp + "/b",
            categories=["empirical-finding", "hypothesis", "question", "method-note"]
        )
        section("PACKET B — Category misuse")
        print("  Scenario: user confuses categories.")

        r = nb2.add_entry("Is superadditivity substrate-independent?", "empirical-finding", "rishi")
        show("Question filed as empirical-finding (wrong)", r)
        # Should be admitted — substrate can't detect semantic misuse, only schema gaps

        r = nb2.add_entry("We should redesign the experiment pipeline.", "hypothesis", "rishi")
        show("Action item filed as hypothesis (wrong)", r)
        # Should be admitted — substrate can't detect this misuse

        r = nb2.add_entry("We should redesign the experiment pipeline.", "todo", "rishi")
        show("Same item in unknown category 'todo' (gap)", r)
        # Should surface as ObservationGap

        print("\n  Note: Packets A+B reveal the limits of structural governance.")
        print("  Semantic misuse (wrong category for semantically wrong reason) is")
        print("  NOT detectable without LLM/embeddings — prohibited by Appendix B.")
        print("  This is an honest limitation. Documented in OBSERVATION_GAP.md §6.")

        # ------------------------------------------------------------------
        # Packet C — Malformed / edge-case content
        # ------------------------------------------------------------------
        nb3 = GovernedNotebook(
            storage_path=tmp + "/c",
            categories=["empirical-finding", "hypothesis", "question", "method-note"]
        )
        section("PACKET C — Malformed / edge-case content")

        r = nb3.add_entry("", "empirical-finding", "rishi")
        show("Empty string content", r)

        r = nb3.add_entry("   ", "empirical-finding", "rishi")
        show("Whitespace-only content", r)

        r = nb3.add_entry("A" * 10000, "empirical-finding", "rishi")
        show("10,000 character content", r)

        r = nb3.add_entry({"nested": {"dict": True}, "list": [1, 2, 3]}, "empirical-finding", "rishi")
        show("Nested dict content (non-string)", r)

        r = nb3.add_entry(["list", "content"], "hypothesis", "rishi")
        show("List content in hypothesis (plural category)", r)

        print("\n  All edge cases should be admitted or handled gracefully — no crashes.")

        # ------------------------------------------------------------------
        # Packet D — Superseded conclusions
        # Earlier finding explicitly overridden by a later one.
        # ------------------------------------------------------------------
        nb4 = GovernedNotebook(
            storage_path=tmp + "/d",
            categories=["empirical-finding", "hypothesis", "question", "method-note"]
        )
        section("PACKET D — Superseded conclusions")
        print("  Scenario: Session 028 finding overridden by Session 073.")

        r1 = nb4.add_entry(
            "Superadditivity is a universal law holding across all substrate types.",
            "empirical-finding", "Session-028"
        )
        show("S028 belief (wrong)", r1)

        r2 = nb4.add_entry(
            "Superadditivity is regime-bounded: abrupt only. Attenuates for continuous drift.",
            "empirical-finding", "Session-073/INSIGHT-114"
        )
        show("S073 correction (contradicts S028)", r2)

        contras_d = nb4.list_contradictions("empirical-finding")
        print(f"\n  Quarantine records: {len(contras_d)}")
        print(f"  Both the wrong belief and the correction are preserved.")
        print(f"  Retraction (marking S028 as superseded) is v0.1 — manual via AdmissionGateway.retract().")

        # ------------------------------------------------------------------
        # Packet E — Exact duplicate
        # Same content proposed twice.
        # ------------------------------------------------------------------
        nb5 = GovernedNotebook(
            storage_path=tmp + "/e",
            categories=["empirical-finding", "hypothesis", "question", "method-note"]
        )
        section("PACKET E — Exact duplicate")
        print("  Scenario: user accidentally enters the same finding twice.")

        content = "Fail-closed governance prevents silent knowledge corruption."
        r1 = nb5.add_entry(content, "empirical-finding", "session-060")
        show("First entry", r1)

        r2 = nb5.add_entry(content, "empirical-finding", "session-060")
        show("Exact duplicate (same content + same source)", r2)

        r3 = nb5.add_entry(content, "empirical-finding", "session-080")
        show("Same content, different source", r3)

        print("\n  Duplicates: same content hash = no conflict detected.")
        print("  The substrate treats identical content as idempotent — correct behaviour.")

        # ------------------------------------------------------------------
        # Summary
        # ------------------------------------------------------------------
        section("STRESS TEST SUMMARY")
        print("""
  Packet A (rapid corrections): substrate quarantines each conflicting version.
    No silent overwriting. All three belief states preserved.

  Packet B (category misuse): substrate admits semantic misuse — it cannot
    detect that a question was filed as a finding. This is an honest limit.
    Schema gaps (unknown category names) are caught; semantic errors are not.

  Packet C (malformed content): substrate handles edge cases gracefully.
    Empty strings, large content, nested structures all processed without crash.

  Packet D (superseded conclusions): both the wrong belief and the correction
    are preserved in quarantine. Retraction is manual for v0.1.

  Packet E (duplicates): exact duplicates are idempotent — no spurious conflict.
    Same content hash = no contradiction, regardless of source.

  Kill Test integrity: the organic Kill Test (test_kill_condition.py) remains
  the primary evaluation. This stress test confirms the substrate handles
  adversarial input correctly — it does not substitute for sustained real use.
        """)


def test_adversarial_stress() -> None:
    """Pytest entry point."""
    run_adversarial_stress()


if __name__ == "__main__":
    run_adversarial_stress()
